In [4]:
# numpy is an array used to represent multidimentional array
#fullform is numerical python 


In [5]:
import numpy as np
l=[1,2,3,4,5,6,7,8]
a= np.array(l)
print(a)

[1 2 3 4 5 6 7 8]


In [6]:
l=[1,2,3,4,5,6,7,8]
a= np.array(l)
l1=[10,11,12,13,14,15,16,17]
b=np.array(l1)
c=a+b #add garna dimension haru same huna parxa
c

array([11, 13, 15, 17, 19, 21, 23, 25])

In [7]:
print(a+5)

[ 6  7  8  9 10 11 12 13]


In [8]:
print(a*5)

[ 5 10 15 20 25 30 35 40]


In [9]:
print(a/5)

[0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6]


In [11]:
a.shape

(8,)

In [15]:
#for 2d array 
l1=[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]
d=np.array(l1)
print(d.shape)
print(d.dtype)

(3, 5)
int32


In [17]:
#for 3d array
l1=[[[1],[2],[3],[4],[5]],[[6],[7],[8],[9],[10]],[[11],[12],[13],[14],[15]]]
e=np.array(l1)
# print(e)
print(e.shape) #(3,5,1) auxa output meaning yesma 3ta rows 5 columns and in each column there are 1 element

(3, 5, 1)


In [22]:
#to reshape an array 
f=np.array([[1,2,3],[4,5,6]])
print(f.shape)
print(f.reshape(3,2))

(2, 3)
[[1 2]
 [3 4]
 [5 6]]


In [24]:
# sequential/vector data ma convert garda flatten garne
f.flatten()

array([1, 2, 3, 4, 5, 6])

In [27]:
#horizontal stack and verticle stack using hstack and stack:
#used to concatinate numpy array (2ta image lai single ma banaune)
print(np.vstack((a,b))) #vertically concatinate garxa dimension of matrix in row badauxa
print(np.hstack((a,b)))#horizontally stack garxa(column badaune similar to list concatination )

[[ 1  2  3  4  5  6  7  8]
 [10 11 12 13 14 15 16 17]]
[ 1  2  3  4  5  6  7  8 10 11 12 13 14 15 16 17]


In [28]:
#random package (used to generate random matrix or a random numpy array)

print(np.random.rand(5,5))

[[0.72503745 0.27978864 0.00965894 0.93802872 0.17430504]
 [0.123706   0.74110727 0.83132376 0.49290511 0.18726291]
 [0.48130594 0.55046161 0.43835678 0.92179788 0.38168108]
 [0.49558742 0.24551888 0.66151831 0.09387677 0.00244475]
 [0.68246877 0.33488287 0.76482141 0.01147374 0.84473171]]


In [34]:
#to generate random integer matrix
# syntax:
#     np.random.randint(starting of number to ending, size=[row,column])
print(np.random.randint(0,10,size=[3,3]))  #0 dekhi 9 samma ko value halera banauxa
print("NEXT MATRIX:")
print(np.random.randint(80,121,size=[3,3])) #80 dekhi 120 samma

[[1 3 3]
 [6 6 1]
 [1 7 0]]
NEXT MATRIX:
[[ 96 109  99]
 [ 97 112 120]
 [ 93 102 109]]


In [37]:
#pick 10 items from a given list with equal probability we use random.choice(Similar to python)
print(np.random.choice(['a','e','i','o','u'],size=10))

['a' 'e' 'a' 'u' 'u' 'a' 'u' 'e' 'u' 'e']


In [39]:
#pick 10 items from a given list with predefined probability "P" 
print(np.random.choice(['a','e','i','o','u'],size=10,p=[0.3,0.1,0.2,0.3,0.1]))

['a' 'a' 'e' 'o' 'i' 'o' 'a' 'o' 'o' 'o']


In [41]:
#if we have to generate a random word or a key or a password using a e i o u then 
"".join(np.random.choice([1,2,3,4,5,6,7,8,9,0,'a','e','i','o','u'],size=10))

'106u54135a'

In [46]:
a=np.array([1,2,3,4,5,6,7,8])
print("Minimum value: ",a.min()) #or np.min(a)
print("Maximum value: ",a.max()) #or np.max(a)
print("Mean value: ",a.mean()) #or np.mean(a)
print("median value: ",np.median(a))
print("standard deviation value: ",np.std(a))

Minimum value:  1
Maximum value:  8
Mean value:  4.5
median value:  4.5
standard deviation value:  2.29128784747792


In [52]:
#TO calculate DETERMINANT Of a matrix, we use det() function from scipy.linalg module.
#linalg le chai linear algebra ko nikalxa

import scipy.linalg as slin
import numpy as np
a=np.array([[3,-4,5],[5,6,-1],[3,4,8]])
slin.det(a)

338.00000000000006

In [54]:
#to calculate trace for same matrix a 
np.trace(a)

17

In [55]:
#to calculate inverse of a matrix
slin.inv(a)

array([[ 0.15384615,  0.15384615, -0.07692308],
       [-0.12721893,  0.02662722,  0.08284024],
       [ 0.00591716, -0.07100592,  0.11242604]])

In [64]:
#matrix multiplication 
MA=np.matrix([[  9, -12,  15],
            [ 10,  12,  -2],
            [ -3,  -4,  -8]])
MB=np.matrix([[3],[5],[-1]])
print(MA*MB)

[[-48]
 [ 92]
 [-21]]
